#!/bin/bash
LOOP=loop3
# 1. Formatting new image with disk partition table...
echo 1. Formatting new image with disk partition table...
IMG_SIZE=$(expr 1024 \* 1024 \* 1024)
dd if=/dev/zero of=/os/dock2vm.img bs=${IMG_SIZE} count=1
sfdisk /os/dock2vm.img <<EOF
label: dos
label-id: 0x5d8b75fc
device: new.img
unit: sectors

linux.img1 : start=2048, size=2095104, type=83, bootable
EOF
# 2. Setting up loop device for new ext3 filesystem...
echo 2. Setting up loop device for new ext3 filesystem...
OFFSET=$(expr 512 \* 2048)
losetup -o ${OFFSET} /dev/$LOOP /os/dock2vm.img
mkfs.ext3 /dev/$LOOP
# 3. Mounting device and extracting filesystem...
echo 3. Mounting device and extracting filesystem...
mkdir /os/mnt
mount -t auto /dev/$LOOP /os/mnt/
tar -xvf /os/dock2vm.tar -C /os/mnt/ > /dev/null
# 4. Installing bootloader and unmounting image...
echo Installing bootloader and unmounting image...
apt-get update -y
apt-get install -y extlinux
extlinux --install /os/mnt/boot
# 5. Writing boot configuration...
echo Writing boot configuration...
cat > /os/mnt/boot/syslinux.cfg <<EOF
DEFAULT linux
  SAY Now booting the kernel from SYSLINUX...
 LABEL linux
  KERNEL /vmlinuz
  APPEND ro root=/dev/sda1 initrd=/initrd.img
EOF
# 6. Capturing image file and unmounting...
echo Capturing image file and unmounting...
dd if=/usr/lib/syslinux/mbr/mbr.bin of=/os/dock2vm.img bs=440 count=1 conv=notrunc
umount /os/mnt
losetup -d /dev/$LOOP
